anything = input ('Digite qualquer coisa: ')
print('Tem número?', anything.isnumeric())
print('Tem número ou letra?', anything.isalnum())
print('Tem letra?', anything.isalpha())
print('Tem número decimal?', anything.isdecimal())
print('Só contém números?', anything.isdigit())
print('Pode ser usado como identificador?', anything.isidentifier())
print('Todas as letras são minusculas?', anything.islower())
print('É imprimível?', anything.isprintable())
print('Todas as letras são maiusculas?', anything.isupper())
print('A primeira letra é maiuscula?', anything.istitle())
print('Tem espaço?', anything.isspace())
print('São todas caracteres ASCCI?', anything.isascii())