num = int(input('Insira um número e descubra sua tabuada: '))
x1 = num * 1
x2 = num * 2
x3 = num * 3
x4 = num * 4
x5 = num * 5
x6 = num * 6
x7 = num * 7
x8 = num * 8
x9 = num * 9
x10 = num * 10

print('{} * 1 = {}'.format(num, x1))
print('{} * 2 = {}'.format(num, x2))
print('{} * 3 = {}'.format(num, x3))
print('{} * 4 = {}'.format(num, x4))
print('{} * 5 = {}'.format(num, x5))
print('{} * 6 = {}'.format(num, x6))
print('{} * 7 = {}'.format(num, x7))
print('{} * 8 = {}'.format(num, x8))
print('{} * 9 = {}'.format(num, x9))
print('{} * 10 = {}'.format(num, x10))
